# Generated by Django 3.2 on 2024-02-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('purchase_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
