# Generated by Django 3.2 on 2024-02-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='num_shares',
            field=models.IntegerField(default=0),
        ),
    ]
